--Creación de las tablas en la base de datos
CREATE TABLE "DUMMY_BLOCKS" 
   (	"BLOCK_ID" NUMBER, 
	"STATUS_BLOCK" NUMBER(1,0), 
	"INFORMATION" VARCHAR2(1024 BYTE), 
	 PRIMARY KEY ("BLOCK_ID")
	 );
 
	 CREATE TABLE "DUMMY_COMMANDS" 
   (	"COMMAND_ID" NUMBER, 
	"COMMAND" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("COMMAND_ID")
	 );
	 
	 CREATE TABLE "DUMMY_DIRECTORY" 
   (	"DIRECTORY_ID" NUMBER NOT NULL ENABLE, 
	"DIRECTORY_NAME" VARCHAR2(50 BYTE), 
	"INODE_ID" NUMBER, 
	"BLOCK_NUMBER" NUMBER, 
	"FATHER_DIRECTORY" NUMBER, 
	"PROPIETARIO" NUMBER, 
	 PRIMARY KEY ("DIRECTORY_ID")
	 );
	 
	 CREATE TABLE "DUMMY_FILES" 
   (	"FILE_ID" NUMBER NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"DIRECTORY_ID" NUMBER, 
	"INODE_ID" NUMBER, 
	"BLOCK_ID" NUMBER, 
	"PROPIETARIO" NUMBER, 
	 PRIMARY KEY ("FILE_ID")
	 );
	 
	 CREATE TABLE "DUMMY_INODES" 
   (	"INODE_ID" NUMBER, 
	"TAMANO" NUMBER, 
	"TIPO" VARCHAR2(20 BYTE), 
	"FECHA" DATE, 
	"PROPIETARIO" NUMBER, 
	"STATUS_INODE" NUMBER(1,0), 
	 PRIMARY KEY ("INODE_ID")
	 );
	 
	 CREATE TABLE ."DUMMY_USERS" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(15 BYTE), 
	 PRIMARY KEY ("USER_ID");
